name: ml flow 
on: 
 push:
  branches: [main] 
jobs:
  validate:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: python steup 
      uses: actions/setup-python@v5
      with:
       python-version: "3.10"
    - name: install dependcise 
      run: |
       pip install -r requriments.txt 
    - name: train and log
      env:
        MLFLOW_TRACKING_URI: ${{secrets.MLFLOW_TRACKING_URI}}
      run: python train.py 
    - name: upload artfiact
      uses: actions/upload-artifact@v4
      with:
       name: model-info
       path: model-info.txt
  deploy: 
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/chechout@v4
    - name: setup
      uses: actions/setup-pthon@v5
      with:
       python-version: "3.10"
    - name: requriments 
      run: |
       pip install -r requriments.txt
    - name: downlaod artifact 
      uses: actions/download-artifact@v4
      with:
        name: model-info
    - name: check 
      env:
        MLFLOW_TRACKING_URI: ${{secrets.MLFLWO_TRACKING_URI}}
      run: python check_threshold.py

    - name: simulate
      run: |
       echo "Builing docker iamge ::$(cat.model_info.txt)"
    
    
    
     
    
  
